// src/App.jsx
import { useState, useEffect } from 'react';
import { GAMES, RECENTLY_PLAYED } from './data';
import { Sidebar, MobileNav, TopBar, PromoRibbon, Hero, RewardsBanner, Promos, Rail, CategoryView, FilteredGrid, Leaderboard, Tournaments, Sports, Promotion, Providers, Footer, GameModal, CustomerServiceModal, SignInModal } from './components';
import { AccountOverview, DepositPage, WithdrawalPage, SupportPage, RecordTable, PersonalInfo, SecurityCenter, CustomerServicePage } from './account-pages';
import { useTweaks, TweaksPanel, TweakSection, TweakSlider, TweakToggle, TweakRadio, TweakColor } from './tweaks-panel';

const TWEAK_DEFAULTS = {
  "theme": "dark",
  "accent": "#2473ff",
  "density": "comfy",
  "aspect": 1.1,
  "showPromos": true,
  "sidebarCollapsed": false
};

const ACCENT_PALETTES = {
  '#1fd373': { a2: '#29e8a3', a3: '#b6f37c' },
  '#2473ff': { a2: '#38bdf8', a3: '#fbbf24' },
  '#7c5cff': { a2: '#22d3ee', a3: '#fbbf24' },
  '#22d3ee': { a2: '#2473ff', a3: '#fbbf24' },
  '#f472b6': { a2: '#38bdf8', a3: '#fde68a' },
  '#fb923c': { a2: '#f472b6', a3: '#facc15' }
};

function App() {
  const [t, setTweak] = useTweaks(TWEAK_DEFAULTS);
  const [activeTab, setActiveTab] = useState('Casino');
  const [activeCat, setActiveCat] = useState('Lobby');
  const [catTab, setCatTab] = useState('Lobby');
  const [openGame, setOpenGame] = useState(null);
  const [showSignIn, setShowSignIn] = useState(false);
  const [showSupport, setShowSupport] = useState(false);
  const [balance, setBalance] = useState(1284.32);
  const [user, setUser] = useState(null);
  const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false);

  // scroll to top when navigating between sections/pages
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, [activeCat]);

  // simulate small balance fluctuation
  useEffect(() => {
    const i = setInterval(() => setBalance(b => +(b + (Math.random() * 4 - 1.7)).toFixed(2)), 5500);
    return () => clearInterval(i);
  }, []);

  // apply theme + tweaks to root vars
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', t.theme);
    const r = document.documentElement.style;
    r.setProperty('--accent', t.accent);
    const palette = ACCENT_PALETTES[t.accent] || ACCENT_PALETTES['#7c5cff'];
    r.setProperty('--accent-2', palette.a2);
    r.setProperty('--accent-3', palette.a3);
    r.setProperty('--card-aspect', t.aspect);
  }, [t.theme, t.accent, t.aspect]);

  return (
    <div className={`shell ${t.sidebarCollapsed ? 'collapsed' : ''} ${mobileSidebarOpen ? 'mobile-open' : ''}`}>
      <div className="sidebar-backdrop" onClick={() => setMobileSidebarOpen(false)}></div>
      <Sidebar collapsed={t.sidebarCollapsed}
               setCollapsed={(fn) => setTweak('sidebarCollapsed', typeof fn === 'function' ? fn(t.sidebarCollapsed) : fn)}
               activeCat={activeCat} setActiveCat={(c) => { setActiveCat(c); setMobileSidebarOpen(false); }}
               activeTab={activeTab} setActiveTab={setActiveTab}
               user={user} onSignIn={() => setShowSignIn(true)} onSupport={() => setShowSupport(true)} />
      <div className="shell-main">
      <TopBar onSignIn={() => setShowSignIn(true)} balance={balance}
              user={user} onLogout={() => setUser(null)}
              onHome={() => { setActiveCat('Lobby'); setCatTab('Lobby'); }}
              setActiveCat={setActiveCat} />
      <main className="container" style={{paddingBottom: 24}}>
        {activeCat === 'Account Overview' && (
          <AccountOverview user={user} balance={balance} setActiveCat={setActiveCat} />
        )}
        {activeCat === 'DepositForm' && (
          <DepositPage setActiveCat={setActiveCat} />
        )}
        {activeCat === 'WithdrawalForm' && (
          <WithdrawalPage setActiveCat={setActiveCat} user={user} />
        )}
        {['Betting Record','Deposit Record','Profit And Loss','Withdrawal Record','Account Record'].includes(activeCat) && (
          <RecordTable title={activeCat} setActiveCat={setActiveCat} />
        )}
        {activeCat === 'Support' && (
          <SupportPage setActiveCat={setActiveCat} />
        )}
        {activeCat === 'Personal Info' && (
          <PersonalInfo user={user} setActiveCat={setActiveCat} />
        )}
        {activeCat === 'Security Center' && (
          <SecurityCenter setActiveCat={setActiveCat} onLogout={() => setUser(null)} />
        )}
        {activeCat === 'Customer Service' && (
          <CustomerServicePage setActiveCat={setActiveCat} />
        )}
        {(activeCat === 'Lobby' || !['Account Overview','Deposit Record','Withdrawal Record','DepositForm','WithdrawalForm','Support','Betting Record','Profit And Loss','Account Record','Personal Info','Security Center','Customer Service'].includes(activeCat)) && <>
        <Hero />
        {t.showPromos && <PromoRibbon />}
        {user && <RewardsBanner user={user} />}
        {t.showPromos && <Promos active={catTab} setActive={setCatTab} />}
        {catTab === 'Lobby' && <>
          <Rail title="Recently played" games={RECENTLY_PLAYED} onOpen={setOpenGame}
                density={t.density} count={RECENTLY_PLAYED.length} />
          <Rail title="Slots"      icon="fire" games={GAMES.slots}     onOpen={setOpenGame} density={t.density} />
          <Rail title="Live Casino" icon="bolt" games={GAMES.live}      onOpen={setOpenGame} density={t.density} />
        </>}
        {catTab === 'Hot Games' && (
          <CategoryView title="Hot Games" icon="fire"
                games={[...GAMES.slots, ...GAMES.live, ...GAMES.originals]}
                onOpen={setOpenGame} density={t.density} />
        )}
        {catTab === 'Mini Games' && (
          <CategoryView title="Mini Games" icon="star" games={GAMES.originals} onOpen={setOpenGame} density={t.density} />
        )}
        {catTab === 'Slots' && (
          <CategoryView title="Slots" icon="fire" games={GAMES.slots} onOpen={setOpenGame} density={t.density} />
        )}
        {catTab === 'Live' && (
          <CategoryView title="Live" icon="bolt" games={GAMES.live} onOpen={setOpenGame} density={t.density} />
        )}
        {catTab === 'Fish' && (
          <CategoryView title="Fish" games={GAMES.slots} onOpen={setOpenGame} density={t.density} />
        )}
        {catTab === 'Promotion' && (
          <Promotion />
        )}
        {catTab === 'Sports' && (
          <Sports />
        )}
        {catTab !== 'Promotion' && catTab !== 'Sports' && catTab !== 'Hot Games' && catTab !== 'Mini Games' && catTab !== 'Slots' && catTab !== 'Live' && catTab !== 'Fish' && <>
        <FilteredGrid onOpen={setOpenGame} density={t.density} />
        <Tournaments />
        <Promotion />
        </>}
        </>}
      </main>
      <Footer />
      <MobileNav catTab={catTab} setCatTab={setCatTab}
                 onBrowse={() => setMobileSidebarOpen(o => !o)}
                 mobileSidebarOpen={mobileSidebarOpen}
                 setActiveCat={setActiveCat}
                 onCloseSidebar={() => setMobileSidebarOpen(false)} />

      </div>
      {openGame && <GameModal game={openGame} onClose={() => setOpenGame(null)} />}
      {showSignIn && <SignInModal onClose={() => setShowSignIn(false)} onLogin={setUser} />}
      {showSupport && <CustomerServiceModal onClose={() => setShowSupport(false)} />}

      <TweaksPanel>
        <TweakSection label="Theme" />
        <TweakRadio label="Mode" value={t.theme} options={['dark','light']}
                    onChange={(v) => setTweak('theme', v)} />
        <TweakColor label="Accent" value={t.accent}
                    options={['#1fd373','#2473ff','#22d3ee','#f472b6','#fb923c']}
                    onChange={(v) => setTweak('accent', v)} />

        <TweakSection label="Game cards" />
        <TweakRadio label="Density" value={t.density} options={['compact','regular','comfy']}
                    onChange={(v) => setTweak('density', v)} />
        <TweakSlider label="Card ratio" value={t.aspect} min={0.6} max={1.2} step={0.01}
                     onChange={(v) => setTweak('aspect', v)} />

        <TweakSection label="Layout" />
        <TweakToggle label="Show promo strip" value={t.showPromos}
                     onChange={(v) => setTweak('showPromos', v)} />
        <TweakToggle label="Collapse sidebar" value={t.sidebarCollapsed}
                     onChange={(v) => setTweak('sidebarCollapsed', v)} />
      </TweaksPanel>
    </div>
  );
}

export default App;

// vue3-app/src/App.vue
<template>
  <AppLayout
    :sidebar-collapsed="sidebarCollapsed"
    :mobile-sidebar-open="mobileSidebarOpen"
    @close-sidebar="mobileSidebarOpen = false"
  >
    <!-- 側邊欄 -->
    <template #sidebar>
      <Sidebar
        v-model:collapsed="sidebarCollapsed"
        v-model:activeCat="activeCat"
        :user="user"
        @sign-in="showSignIn = true"
        @support="showSupport = true"
      />
    </template>

    <!-- 頂部列 -->
    <template #header>
      <TopBar
        :user="user"
        :balance="balance"
        @sign-in="showSignIn = true"
        @logout="user = null"
        @home="activeCat = 'Lobby'"
        @navigate="(cat) => activeCat = cat"
      />
    </template>

    <!-- Account pages -->
    <AccountOverview v-if="activeCat === 'Account Overview'"
      :user="user" :balance="balance"
      @navigate="activeCat = $event"
    />
    <DepositPage v-else-if="activeCat === 'DepositForm'"
      @navigate="activeCat = $event"
    />
    <WithdrawalPage v-else-if="activeCat === 'WithdrawalForm'"
      :user="user"
      @navigate="activeCat = $event"
    />
    <PersonalInfo v-else-if="activeCat === 'Personal Info'"
      :user="user"
      @navigate="activeCat = $event"
    />
    <SecurityCenter v-else-if="activeCat === 'Security Center'"
      @navigate="activeCat = $event"
      @logout="user = null; activeCat = 'Lobby'"
    />
    <CustomerServicePage v-else-if="activeCat === 'Customer Service'"
      @navigate="activeCat = $event"
    />
    <RecordTable v-else-if="['Betting Record','Deposit Record','Withdrawal Record','Profit And Loss','Account Record'].includes(activeCat)"
      :title="activeCat"
      @navigate="activeCat = $event"
    />
    <SupportPage v-else-if="activeCat === 'Support'"
      @navigate="activeCat = $event"
    />

    <!-- 首頁區塊 -->
    <template v-else-if="activeCat === 'Lobby'">
      <Hero />
      <PromoRibbon v-if="showPromos" />
      <RewardsBanner v-if="user" :user="user" />
      <Promos v-if="showPromos" v-model:active="catTab" />

      <!-- Lobby tab -->
      <template v-if="catTab === 'Lobby'">
        <Rail title="Recently played" :games="RECENTLY_PLAYED" :count="RECENTLY_PLAYED.length" @open="openGame = $event" />
        <Rail title="Slots"       icon="fire" :games="GAMES.slots" @open="openGame = $event" />
        <Rail title="Live Casino" icon="bolt" :games="GAMES.live"  @open="openGame = $event" />
        <FilteredGrid @open="openGame = $event" />
        <Leaderboard />
        <Tournaments />
        <Promotion />
        <Providers />
      </template>

      <!-- Hot Games tab -->
      <CategoryView v-else-if="catTab === 'Hot Games'"
        title="Hot Games" icon="fire"
        :games="[...GAMES.slots, ...GAMES.live, ...GAMES.originals]"
        @open="openGame = $event"
      />

      <!-- Mini Games tab -->
      <CategoryView v-else-if="catTab === 'Mini Games'"
        title="Mini Games" icon="star"
        :games="GAMES.originals"
        @open="openGame = $event"
      />

      <!-- Slots tab -->
      <CategoryView v-else-if="catTab === 'Slots'"
        title="Slots" icon="fire"
        :games="GAMES.slots"
        @open="openGame = $event"
      />

      <!-- Live tab -->
      <CategoryView v-else-if="catTab === 'Live'"
        title="Live" icon="bolt"
        :games="GAMES.live"
        @open="openGame = $event"
      />

      <!-- Fish tab -->
      <CategoryView v-else-if="catTab === 'Fish'"
        title="Fish"
        :games="GAMES.slots"
        @open="openGame = $event"
      />

      <!-- Sports tab -->
      <Sports v-else-if="catTab === 'Sports'" />

      <!-- Promotion tab -->
      <Promotion v-else-if="catTab === 'Promotion'" />

      <!-- Fallback -->
      <div v-else style="color:var(--text-dim);padding:40px 0;text-align:center;font-family:var(--font-mono);font-size:13px">
        {{ catTab }} — coming soon
      </div>
    </template>

    <!-- 其他主頁 -->
    <div v-else style="color:var(--text);padding:40px 0;font-family:var(--font-display)">
      <h2>{{ activeCat }}</h2>
    </div>

    <!-- 頁尾 -->
    <template #footer>
      <AppFooter />
    </template>

    <!-- 手機底部導覽 -->
    <template #mobile-nav>
      <MobileNav
        :cat-tab="catTab"
        :mobile-sidebar-open="mobileSidebarOpen"
        @browse="mobileSidebarOpen = !mobileSidebarOpen"
        @close-sidebar="mobileSidebarOpen = false"
        @navigate="({ cat, tab }) => { activeCat = cat; if (tab) catTab = tab; }"
      />
    </template>
  </AppLayout>

  <!-- Modals -->
  <GameModal
    v-if="openGame"
    :game="openGame"
    @close="openGame = null"
  />
  <SignInModal
    v-if="showSignIn"
    @close="showSignIn = false"
    @login="user = $event"
  />
  <CustomerServiceModal
    v-if="showSupport"
    @close="showSupport = false"
  />
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue';
import AppLayout      from '@/layouts/AppLayout.vue';
import Sidebar        from '@/components/layout/Sidebar.vue';
import TopBar         from '@/components/layout/TopBar.vue';
import AppFooter      from '@/components/layout/AppFooter.vue';
import MobileNav      from '@/components/layout/MobileNav.vue';
import Hero           from '@/components/home/Hero.vue';
import PromoRibbon    from '@/components/home/PromoRibbon.vue';
import RewardsBanner  from '@/components/home/RewardsBanner.vue';
import Promos         from '@/components/home/Promos.vue';
import Rail           from '@/components/game/Rail.vue';
import FilteredGrid   from '@/components/game/FilteredGrid.vue';
import CategoryView   from '@/components/game/CategoryView.vue';
import Leaderboard            from '@/components/lobby/Leaderboard.vue';
import Tournaments            from '@/components/lobby/Tournaments.vue';
import Sports                 from '@/components/lobby/Sports.vue';
import Promotion              from '@/components/lobby/Promotion.vue';
import Providers              from '@/components/lobby/Providers.vue';
import GameModal              from '@/components/modal/GameModal.vue';
import SignInModal            from '@/components/modal/SignInModal.vue';
import CustomerServiceModal   from '@/components/modal/CustomerServiceModal.vue';
import AccountOverview        from '@/components/account/AccountOverview.vue';
import DepositPage            from '@/components/account/DepositPage.vue';
import WithdrawalPage         from '@/components/account/WithdrawalPage.vue';
import PersonalInfo           from '@/components/account/PersonalInfo.vue';
import SecurityCenter         from '@/components/account/SecurityCenter.vue';
import CustomerServicePage    from '@/components/account/CustomerServicePage.vue';
import RecordTable            from '@/components/account/RecordTable.vue';
import SupportPage            from '@/components/account/SupportPage.vue';
import { GAMES, RECENTLY_PLAYED } from '@/data/index.js';

const openGame          = ref(null);
const sidebarCollapsed  = ref(false);
const mobileSidebarOpen = ref(false);
const activeCat         = ref('Lobby');
const catTab            = ref('Lobby');
const showPromos        = ref(true);
const showSignIn        = ref(false);
const showSupport       = ref(false);
const balance           = ref(1284.32);
const user              = ref(null);

// 模擬餘額浮動
let balanceTimer;
onMounted(()    => { balanceTimer = setInterval(() => { balance.value = +(balance.value + (Math.random() * 4 - 1.7)).toFixed(2); }, 5500); });
onUnmounted(()  => clearInterval(balanceTimer));
</script>
